### ISSUE TITLE
pitch segment doesn't work

### ISSUE THREAD

**Issue by Gleefre** [Shirakumo/libmixed#15]
As reported in https://github.com/Shirakumo/harmony/issues/23 , pitch segment doesn't work.

**Comment by Gleefre** [comment]
It seems that `make_pitch_data` incorrectly allocates memory regions, I was able to fix it by increasing size in 4 times.

**Comment by Shinmera** [comment]
I've known about this for ages and never got around to fixing it. Thanks for picking up my slack!
