### ISSUE TITLE
libmixed support real time communication?

### ISSUE THREAD

**Issue by airx** [Shirakumo/libmixed#3]
File mixer is different from RTC mixer.
RTC mixer may needs flow control , sometime it needs drop some channel's buffer which received too much, etc. But file mixer doesn't have these problems, just mix each channel buffer.
So I want ask if libmixed support rtc mix or not?

**Comment by Shinmera** [comment]
At the moment the number of samples mixed per round is fixed. If you have a variable number of samples being introduced into the system, you need to implement your own buffering scheme.
